# Generated by Django 6.0.3 on 2026-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_price_deliveryentry_expense_missingstocklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryentry',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='deliveryentry',
            name='rider',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
