# Generated by Django 6.0.5 on 2026-06-25 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_location_alter_deliveryentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='missingstocklog',
            name='missing_stock',
        ),
        migrations.RemoveField(
            model_name='missingstocklog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='missingstocklog',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, help_text='Specific locations an Agent is allowed to access.', related_name='assigned_users', to='core.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('coo', 'COO'), ('cto', 'CTO'), ('cfo', 'CFO'), ('regional_manager', 'Regional Manager'), ('manager', 'Manager'), ('agent', 'Agent'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Region this user is in charge of (Regional Manager).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='core.region'),
        ),
        migrations.DeleteModel(
            name='MissingStock',
        ),
        migrations.DeleteModel(
            name='MissingStockLog',
        ),
    ]
