"""
Django settings for sage_inv project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from decouple import config
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

def _csv_env(key, default=''):
    return [item.strip() for item in config(key, default=default).split(',') if item.strip()]


ALLOWED_HOSTS = _csv_env(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,.diawhiz.com.ng,.herokuapp.com',
)


# Application definition

INSTALLED_APPS = [
    'daphne',  # must precede staticfiles so runserver uses the ASGI/Channels server
    'unfold',  # must precede django.contrib.admin to theme it
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',
    'whitenoise.runserver_nostatic',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS: open in development, explicit allow-list in production.
CORS_ALLOWED_ORIGINS = _csv_env('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_ALL_ORIGINS = DEBUG and not CORS_ALLOWED_ORIGINS

CSRF_TRUSTED_ORIGINS = _csv_env('CSRF_TRUSTED_ORIGINS')

ROOT_URLCONF = 'sage_inv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sage_inv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('AIVEN_DATABASE_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600,
    )
}

AUTH_USER_MODEL = 'core.User'

# Channels (WebSockets) — Redis in production, in-memory for local dev.
ASGI_APPLICATION = 'sage_inv.asgi.application'

REDIS_URL = config('REDIS_URL', default='')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'},
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Security hardening — active when DEBUG is off (i.e. production).
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ── Django admin theme (django-unfold) ──────────────────────────────────────
# Brand colour: Tailwind "blue" scale as space-separated RGB channels.
_BRAND = {
    "50": "239 246 255", "100": "219 234 254", "200": "191 219 254",
    "300": "147 197 253", "400": "96 165 250", "500": "59 130 246",
    "600": "37 99 235", "700": "29 78 216", "800": "30 64 175",
    "900": "30 58 138", "950": "23 37 84",
}

UNFOLD = {
    "SITE_TITLE": "Sage Inventory Admin",
    "SITE_HEADER": "Sage Inventory",
    "SITE_SUBHEADER": _("Inventory & Operations"),
    "SITE_SYMBOL": "inventory_2",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": None,  # None → user can toggle light/dark
    "DASHBOARD_CALLBACK": "core.dashboard.dashboard_callback",
    "COLORS": {"primary": _BRAND},
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Operations"),
                "separator": True,
                "items": [
                    {"title": _("Vendors"), "icon": "storefront",
                     "link": reverse_lazy("admin:core_vendor_changelist")},
                    {"title": _("Products"), "icon": "inventory_2",
                     "link": reverse_lazy("admin:core_product_changelist")},
                    {"title": _("Stock"), "icon": "warehouse",
                     "link": reverse_lazy("admin:core_stock_changelist")},
                    {"title": _("Deliveries"), "icon": "local_shipping",
                     "link": reverse_lazy("admin:core_deliveryentry_changelist")},
                ],
            },
            {
                "title": _("Finance"),
                "separator": True,
                "items": [
                    {"title": _("Expenses"), "icon": "payments",
                     "link": reverse_lazy("admin:core_expense_changelist")},
                ],
            },
            {
                "title": _("Organization"),
                "separator": True,
                "items": [
                    {"title": _("Regions"), "icon": "map",
                     "link": reverse_lazy("admin:core_region_changelist")},
                    {"title": _("Locations"), "icon": "location_on",
                     "link": reverse_lazy("admin:core_location_changelist")},
                ],
            },
            {
                "title": _("Access"),
                "separator": True,
                "items": [
                    {"title": _("Users"), "icon": "person",
                     "link": reverse_lazy("admin:core_user_changelist")},
                    {"title": _("Groups"), "icon": "group",
                     "link": reverse_lazy("admin:auth_group_changelist")},
                    {"title": _("Tokens"), "icon": "key",
                     "link": reverse_lazy("admin:authtoken_tokenproxy_changelist")},
                ],
            },
        ],
    },
}
